# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]
  schedule:
    - cron: '30 10 * * *'

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Install Requeriments
      run: pip install -r requirements.txt
    - uses: actions/checkout@v2
    - name: Test
      run: python3 main.py
